### ISSUE TITLE
Group command (-1) doesn't work

### ISSUE THREAD

**Issue by wizbowes** [nbogojevic/piHomeEasy#2]
Firstly - thanks for this.

Plugs HE830S don't work with this code.

Plugs HE3315 do work.

Both these plugs work fine with remote HE312S.

Additionally the Group command (-1) doesn't with HE312S either.
`piHomeEasy 0 31415 1 on `
works fine
`piHomeEasy 0 31415 -1 on`
does nothing.

**Comment by nbogojevic** [comment]
Thanks for report wizbowes. Did some googling, and many UK home easy sockets use different protocol (some use AC, some use ARC protocol), so this encoding won't work with all of them. Seems that HE3xx and HE4xx work, but not others.

**Comment by wizbowes** [comment]
I managed to get my box working eventually using the code here as a base and copying my remote codes hardcoding everything except for the switch number and the on/off command.  I wasn't able to find a code specification on the internet.  Happy to share the code with you if you're interested or have found the spec.

Great job BTW - your code integrates very easily with Home Assistant

**Comment by NickSee** [comment]
Nenad you are my hero.  I've been working with home auto (home assistant) for a couple of months and my homeasy stuff was a nightmare compared to anything else to try to rf sniff. new receivers, faraday cages pulling hair. Finally stumbled across your code and could forget trying to work with my HE100 remotes and bypass them at least for now, train all my HE3xxx plugs and FINALLY control them from Pi Zero. I am Soooo grateful to you. thank you!

Now need to work out like wizbowes did how to integrate your code with Home Assistant... my first attempt to sniff codes and implement them with Switch: Protocol: Pulselength: Code: being a fail.....

but again thank you so much

Nick (also a UK homeasy user)

PS have successfully and ONLY used group command -1 to train and operate the HE3xx series so far

**Comment by NickSee** [comment]
Guys I'm doing my nut trying to solve this... please help me.. I can issue the command  "sudo /home/pi/piHomeEasy/piHomeEasy 0 31415 -1 on" through VNC session with success, hence so happy in post above.  But when trying to invoke this through Homeassistant I keep getting 'command failed'.

At first I thought it was sudo problem with user 'homeassistant' but even when I locally grant 'homeassistant' with sudo permission I still get command failed. Then I found that 'homeassistant' user seemed to not find the path to 'piHomeEasy' so I added it in /etc/config and also in local path variable. I got to the point where homeassistant (and hass just in case) could run the file with sudo and had access to the right path but STILL when I click on my HA button to run the command_line "sudo /home/pi/piHomeEasy/piHomeEasy 0 31415 -1 on" it fails.

Please help I don't know what to do next.

**Comment by wizbowes** [comment]
Hi NickSee,

My settings in HA for a socket are below:

```
switch:
  platform: command_line
  switches:    
    lounge_leds:
      command_on: "sudo piHomeEasy 0 31415 1 on"
      command_off: "sudo piHomeEasy 0 31415 1 off"
      command_state: ""
      value_template: '{{ return_value == "1" }}'
      friendly_name: Fireplace Lights
    lounge_windows_leds:
      command_on: "sudo piHomeEasy 0 31415 2 on"
      command_off: "sudo piHomeEasy 0 31415 2 off"
      command_state: ""
      value_template: '{{ return_value == "1" }}'
      friendly_name: Lounge Window Lights
```

I think I may have had to give execute permissions to all.  The file you want to execute is not in /home/pi/piHomeEasy/piHomeEasy - it should be in /usr/local/bin.  If it's not there I suspect you missed the line out to install it.  To install it do this (assuming that the code is in /home/pi/piHomeEasy/) :

```
cd /home/pi/piHomeEasy/ 
sudo make install
```

Hope that helps
